[custom]

; 规则引用

ruleset=🧋,https://proxy-rule.010811.xyz/rule/app/tw.ini
ruleset=⛩️,https://proxy-rule.010811.xyz/rule/app/jp.ini
ruleset=📒,https://proxy-rule.010811.xyz/rule/app/hentai.ini
ruleset=📥,https://proxy-rule.010811.xyz/rule/app/da.ini
ruleset=📥,https://d49u.010811.xyz/tgip.txt
ruleset=🍥,https://proxy-rule.010811.xyz/rule/PROXY.ini
ruleset=DIRECT,https://proxy-rule.010811.xyz/rule/DIRECT.ini
ruleset=DIRECT,https://d49u.010811.xyz/cnip.txt
ruleset=🍥,[]FINAL

custom_proxy_group=🍥`select`.*
custom_proxy_group=🧋`select`.*
custom_proxy_group=⛩️`select`.*
custom_proxy_group=📒`select`.*
custom_proxy_group=📥`select`.*

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://proxy-rule.010811.xyz/clash/2_clash_rule_base.ini
