mixed-port: 4949

mode: rule
log-level: silent
ipv6: false
keep-alive-interval: 200
find-process-mode: off
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: qq
global-ua: clash.meta.nine

geodata-mode: true
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: true
  listen: 0.0.0.0:4953
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - 119.29.29.29
    - 180.184.2.2
    - 223.6.6.6
    - 1.2.4.8

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80]
