; play下载
DOMAIN-SUFFIX,xn--ngstr-cn-8za9o.com
DOMAIN-SUFFIX,xn--ngstr-lra8j.com

; youtube
DOMAIN-KEYWORD,youtube
DOMAIN-SUFFIX,ytimg.com
DOMAIN-SUFFIX,googlevideo.com

; 谷歌网盘
DOMAIN,drive.usercontent.google.com

; 魂+网盘
DOMAIN-SUFFIX,gofile.io
DOMAIN-SUFFIX,pixeldrain.com

; twitter
DOMAIN,twimg.com

; hanime1
DOMAIN-SUFFIX,hanime1.me
DOMAIN-SUFFIX,hembed.com

; ins
DOMAIN-SUFFIX,cdninstagram.com

; mega
DOMAIN-SUFFIX,mega.co.nz
DOMAIN-SUFFIX,mega.io
DOMAIN-SUFFIX,mega.nz

; pikpak
DOMAIN-SUFFIX,mypikpak.com
