; 谷歌网盘
DOMAIN,drive.usercontent.google.com

; 魂+网盘
DOMAIN-SUFFIX,gofile.io
DOMAIN-SUFFIX,pixeldrain.com

; mega
DOMAIN-SUFFIX,mega.co.nz
DOMAIN-SUFFIX,mega.io
DOMAIN-SUFFIX,mega.nz

; pikpak
DOMAIN-SUFFIX,mypikpak.com
